# Generated by Django 5.0.6 on 2026-06-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("course", models.CharField(max_length=50)),
                ("score", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
