# Generated by Django 6.0.5 on 2026-06-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("team", models.CharField(max_length=100)),
                ("runs", models.IntegerField()),
                ("dob", models.DateField()),
            ],
        ),
    ]
