# Generated by Django 5.0.6 on 2026-07-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fb",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
